import drools.example.drools.entity.*;
import drools.example.drools.util.DroolsLogger;

global drools.example.drools.entity.Employee employee;

dialect  "mvel"

rule "Fire employee if the employee works less than 40h a week"

    when
        employeeHours: TimeSheet(hours < 40)

    then
        employee.setStatus("Fired");
end


rule "Employee has day off when the manager BOB is at work"

    when
        $employee: Employee($productOwners: productOwners)
        $productOwner: ProductOwner(type.equals("BOB")) from $productOwners

    then
        $employee.setDayOffWork(true);
        DroolsLogger.helper(drools);
end
